"""cria_tabela_pagamentos_e_vencimentos

Revision ID: 3eec1cda7848
Revises: 5174b14499bd
Create Date: 2026-04-03 10:26:27.140577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3eec1cda7848'
down_revision: Union[str, None] = '5174b14499bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_system_settings_key', table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index('ix_admin_audit_logs_id', table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_index('ix_payment_transactions_gateway_hash', table_name='payment_transactions')
    op.drop_index('ix_payment_transactions_id', table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.add_column('subscriptions', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscriptions', sa.Column('last_payment_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'last_payment_date')
    op.drop_column('subscriptions', 'expires_at')
    op.create_table('payment_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gateway_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name='payment_transactions_plan_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='payment_transactions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='payment_transactions_pkey')
    )
    op.create_index('ix_payment_transactions_id', 'payment_transactions', ['id'], unique=False)
    op.create_index('ix_payment_transactions_gateway_hash', 'payment_transactions', ['gateway_hash'], unique=False)
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('target_entity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name='admin_audit_logs_admin_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='admin_audit_logs_pkey')
    )
    op.create_index('ix_admin_audit_logs_id', 'admin_audit_logs', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name='system_settings_pkey')
    )
    op.create_index('ix_system_settings_key', 'system_settings', ['key'], unique=False)
    # ### end Alembic commands ###
