"""add last_reset_date

Revision ID: 5174b14499bd
Revises: f8ecd9a156f0
Create Date: 2026-04-02 12:43:00.327693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5174b14499bd'
down_revision: Union[str, None] = 'f8ecd9a156f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_audit_logs_id', table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_index('ix_system_settings_key', table_name='system_settings')
    op.drop_table('system_settings')
    op.add_column('subscriptions', sa.Column('last_reset_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'last_reset_date')
    op.create_table('system_settings',
    sa.Column('key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name='system_settings_pkey')
    )
    op.create_index('ix_system_settings_key', 'system_settings', ['key'], unique=False)
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('target_entity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name='admin_audit_logs_admin_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='admin_audit_logs_pkey')
    )
    op.create_index('ix_admin_audit_logs_id', 'admin_audit_logs', ['id'], unique=False)
    # ### end Alembic commands ###
